### PR TITLE
Add `Maybe.property` for safe property extraction.

### PR DESCRIPTION
**Pull request by chriskrycho**
So I'm thinking about this and there are two ways to go here with the type of the key – i.e. whether it should be restricted to being a key of the type, or not.

As it is, if you *know* the type of an object and know that a key isn't on the object, then you can forbid access at all:

screen shot 2018-10-24 at 4 00 24 pm

Note that this also works for dictionary types, so I think that's good enough.

We *could* make it work for arbitrary objects (literally things which are just `object` or `extends {}`) but I think that loses *useful* type safety here.

Note that as this stands, it does *not* behave like `_.get`or `_.property`: it only does one layer of lookup. I'm open to input on whether that's the best behavior or not.

### CODE REVIEW

**Comment by chriskrycho** [comment]
@bmakuh I'd love your thoughts on the type-safety/deep lookup tradeoff here as well as general comments. @tansongyang, as you're one of the other people who uses True Myth the most at Olo, your thoughts would also be much appreciated.

The basic tradeoff is: if we support deep property lookups like `_.get` or `_.property` do, we lose all type information. You would *always* have to specify the type:

```ts
Maybe.property<string>('a.b.c.d', someObject);
```

This of course means you're introducing a place where you are telling the compiler "Trust me! I know this is the right type!"

The current approach says that actual type safety is more valuable; the only thing that the above could ever resolve type-checking-wise is an object which happened to be shaped like this:

```ts
const f = {
  ['a.b.c.d']: 'e';
};

Maybe.property('a.b.c.d', f); // Just('e')
```

🤣 This is of course not the point.

But because of the decision to actually check against the keys of the type it's handed, `Maybe.property` *does* have the type-safe lookup properties outlined in the intro comment. My fairly strong inclination is to go with the type-safe version, and to let users do `Maybe.of<string>(_.get(f, 'a.b.c.d'))` instead if that's the behavior they want.

Thoughts?

**Comment by tansongyang** [comment]
I too am in favor of type safety. However, I do think _some_ kind of nice API for nested lookups would be very helpful. If we made this an instance method on `Maybe`, we would be able to do things like this, right?

```TypeScript
const c = Maybe.of(obj).get('a').get('b').get('c'); // `c` would be `Nothing` or `Just<TypeOfC>`
```

It would basically be the [null conditional operator from C#](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-conditional-operators)

**Comment by chriskrycho** [comment]
@tansongyang that's a great suggestion. I built it out, sharing the same name as the top-level function. So your example would look like this:

```ts
const c = Maybe.of(obj)
  .property('a')
  .property('b')
  .property('c');
```

And `c` here would be `Maybe<typeof obj[a][b][c]>`.

**Comment by chriskrycho** [comment]
@tansongyang @bmakuh I just realized we do *not* have a `.get` in the library. Maybe we can use it for this. It would be similar to `_.get` at that point (though with the type-safe qualifications I noted above). The brevity would be nice IMO. Thoughts?

**Comment by chriskrycho** [comment]
Updated that, and good call!

**Comment by chriskrycho** [comment]
One last question here: the functions have up to this point been identical with the methods, so it would need to be `Maybe.get(key, someMaybe)` for that to be so.

This has me thinking: maybe we add *both* `Maybe.property` and `Maybe.get`, with `Maybe.get` being isometric with the method versions `Maybe#get` and `property` being what I have as `get` right now?

**Comment by tansongyang** [comment]
I think I'm not as familiar with the conventions on this, so I'm happy with whatever solution lets us keep `Maybe#get(key)`. To be clear, you're suggesting the following?

```TS
Maybe.property(key, obj)
Maybe.get(key, someMaybe)
Maybe#get(key)
```

**Comment by chriskrycho** [comment]
Exactly that!

**Comment by chriskrycho** [comment]
Updated, including docs. Time to :shipit:!

**Pull request merged**
