### PR TITLE
Don't expose Result.error when it's an Ok

### LINKED ISSUE #323: Result type guard is wrong
In the past this was not possible because the TypeScript compiler did not allow it:

```ts
const foo = ok<string, string>('a');

console.log(foo.error);
```

But with `true-myth` `5.2.0` it is possible and I'm getting a runtime error `Cannot get the error of Ok`. Instead of a runtime error the compiler should warn here and force the type guard `if (foo.isErr) {}`.

### PR DESCRIPTION
**Pull request by screendriver**
Fixes #323

### CODE REVIEW

**Comment by chriskrycho** [comment]
Thanks for opening this! I’m not immediately merging because I am thinking this through a bit—this is actually what I did originally, if I recall correctly, and it *also* had some quirky issues. There's a tradeoff between having `error` be present but `never` (meaning you should not be able to do anything with it) and having it be *absent*. I will mull on it (and cc. @bmakuh!).

**Comment by screendriver** [comment]
If you look at the modified unit tests you can see already that something is wrong in the current implementation. Otherwise the tests as they are on `main` would not be able to compile. For example this line here https://github.com/true-myth/true-myth/blob/ba77078238709261b6f29edeb815d3d95df5ba05/test/result.test.ts#L233 should not compile without a type guard before 🙂

**Comment by chriskrycho** [comment]
If you check the git or PR history, I believe you'll see there's a reason things are the way they are. :) Intuitively, what you’re describing is totally reasonable, but in practice I believe we do things the way we do because we had *other* inference issues otherwise. (I don't have time to dig into it and pull up the details at the moment, but will follow up later this week.)

**Comment by chriskrycho** [comment]
I spent some time with it after publishing 5.3.0 this morning and have updated it very slightly, but net: your change here was correct, so thanks! Should be good to land once CI goes ✅, and I'll release it as 5.3.1 (forgot it was here or I'd have done it as part of 5.3.0!).

**Pull request merged**
