### PR TITLE
Add the ability to use different types for defaults in unwrapOr

### PR DESCRIPTION
**Pull request by alantrick**
See https://github.com/true-myth/true-myth/issues/63. I thought about adding some documentation to src/doc/maybe.md, but I wasn't really sure if it was worth it, or how to write it sensibly. The feature itself is fairly easy enough to discover on its that it might not need clear documentation.

### CODE REVIEW

**Review by chriskrycho — CHANGES_REQUESTED** [review]
Thank you! Two requests here, if you don't mind:

1. For consistency with the rest of the library, let's go with `U` instead of `D`. Totally get where you were coming from in using `D` for "default", but it ends up a bit confusing in the `Result` implementation in particular, where it's right next to `E` a lot—`T` and `U` keeps it clearer that *those* are related.

2. Do you mind adding it for `unwrapOrElse` as well? For symmetry's sake, that makes sense.

Thanks again!

**Comment by alantrick** [comment]
@chriskrycho sorry it took me so long to respond. I don't think I received a notification from github about the feedback. I have no idea why.

Anyways, I made the requested changes :-)

**Comment by chriskrycho** [comment]
No worries—I have been on the other end of that many a time. I’ll take a look sometime in the next couple days!

**Comment by alantrick** [comment]
Bump :-)

**Comment by chriskrycho** [comment]
Thank you! I will cut a minor release with this sometime this week!

**Comment by chriskrycho** [comment]
…or possibly in a major. 😬

**Comment by chriskrycho** [comment]
Published as [v4.1.0](https://github.com/true-myth/true-myth/releases/tag/v4.1.0)!

**Pull request merged**
