### PR TITLE
fix: set error type in `Result.ok` and ok type in `Result.err` to `never` by default

### LINKED ISSUE #788: Return error-free type in the `Result.ok` method
Imagine we have function `someFunc` that takes `Result<...>` as an argument, and we want to infer "ok" and "error" types of this result argument:

```ts
import { Result } from 'true-myth'

function someFunc<Ok extends number, Err extends string>(result: Result<Ok, Err>) {
  // ...
}

someFunc(Result.ok(1))
//        ^ Argument of type 'Result<1, unknown>' is not assignable to parameter of type 'Result<1, string>'.
//            Type 'Ok<1, unknown>' is not assignable to type 'Result<1, string>'.
//              Type 'Ok<1, unknown>' is not assignable to type 'Ok<1, string>'.
//                Type 'unknown' is not assignable to type 'string'.(2345)

someFunc(Result.ok<number, never>(1))
//        ^ all is fine

someFunc(Result.err('error'))
//        ^ Argument of type 'Result<unknown, "error">' is not assignable to parameter of type 'Result<number, "error">'.
//            Type 'Ok<unknown, "error">' is not assignable to type 'Result<number, "error">'.
//              Type 'Ok<unknown, "error">' is not assignable to type 'Ok<number, "error">'.
//                Type 'unknown' is not assignable to type 'number'.(2345)

someFunc(Result.err<never, string>('error'))
//        ^ all is fine
```

[TS Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgJQKYGcCuAbeBfOAMyghDgHIYpNUBaEATxgAtyAoNwzAOwGMZgEbnHSlUAMR68APAHkA1nFQAPGKm4ATdHG6YQAI1RQANHACiUKEtXqtIqsG4BzAHwAKKBhwwAXCi+4cvKmFlAuAJSIbHBwAPSxcAB0yWx4HKIgElJuaFi4iRDybgCM4eFs8TFVVQB6cACCUE566vAQhHAwDGCoFLne0sWmPPLcEADu3C7kcMDaY-AAhujowE7ci-rYvTAQcGCLUIuZalbtnd295P2BQ-ZQjq7kiRUJ1e8xACqXFAqDw9xRhMpjM5joIEsVmsNlsdnsuj0+gEYP97o9pi9Kh9sd9EeQ-ncRmNJtNZvMIXBlqt1pttp14T98fJUegHM4Ma9sVy4LirkTgaDyZDqTC6bsLnjWQ9nM83AAmADMABYAKzlNgZLJ8HLIgrM3QGIymbioABuRncpXKWI+dUW2GwZKIjlQ6TEkm1NxgiSMUDc5F90HIZU52LqjWamW4bQ6CKuXuk-MmpgARIGoCnSWCFpSoTTYfT9odjqhTnBznGkXkUQbDCY4GnLNBM89Q9yeYy-knuKn0y2nTmqdDaXCJfHkdJa0aG32OTb2x28V3AcSezOmxms0LcyKR4XK0zJ3o672Ny3MW8F1VeRRu4LwcLhwXxQep1BZYrVerNR7eDrqz6liTma05Sui-rpsG1qXu8doOk6hAukAA)

The issue is that these type parameters in (`E` in `ok` and `T` in `error`) methods declarations have no default value and are not used in argument types, so they're inferred as `unknown`. Although when calling `Result.ok()` I expect to get `Result<..., never>`, not `Result<..., unknown>`, since the `ok` method by its definition cannot return any errors! 

I suggest adding a default type for type parameters in places like this to avoid those annoying errors:
```diff
-  static ok<T, E>(value: T): Result<T, E>;
+  static ok<T, E = never>(value: T): Result<T, E>;
```
https://github.com/true-myth/true-myth/blob/87e12dd509bbd10e071c96feaa40bfb070b77831/src/result.ts#L87

### PR DESCRIPTION
**Pull request by auvred**
Fixes #788

### CODE REVIEW

**Comment by chriskrycho** [comment]
Thanks, @auvred – I saw this and have not forgotten it, but last week was a super busy week with travel for me, and I have a couple other things on my plate this week, so it will probably be mid-week or so before I get to review it!

**Review by chriskrycho — COMMENTED** [review]
I have spent some time with this today and I still think it is overall a good idea, but I need to mull a bit on what we want to do in terms of merging and releasing it, because it *is* a breaking change.

- All those type assertions are catching something real: anything where variance is at issue *will* be tripped by this change. The easiest ways to see this (besides the type tests!) is code like this:

    ```ts
    declare let oldVersion: Array<Result<unknown, string>>;
    let newVersion: Array<Result<never, string>> = oldVersion;
    ```
    
    This does not type check! You’ll see the same with variance issues around callbacks, too.

- Anything which happened to rely (explicitly or implicitly) on the fact that `.error` was `unknown` in an `Ok` and vice versa will now break.

We generally try not to make *too* many breaking changes, but a major release once a year isn’t too bad, and this seems like a big enough win to warrant it. I just want to think about whether there are other things we should bundle along with that, and if so what the timing should be! I will likely merge it soon, but also wanted to get @bmakuh’s thoughts here; I also just wanted you to know it is not forgotten about!

**Comment by auvred** [comment]
Yeah, I can see that this update makes breaking changes for existing lib users, so I'm fine with it even if you reject this PR. It's all up to you!

**Comment by bmakuh** [comment]
It seems like a good change to me, and like you said we haven't had a breaking change for over a year. It doesn't seem like the most painful of breaking changes, either: the fix is just to provide explicit type params where they were inferred before. It's not like some radical change of the API surface. So IMO I'd say it seems like an 8.x release is fine. I can't think of anything else that ought to be included 🤷‍♂️

**Comment by chriskrycho** [comment]
👍🏼 I’ll ship it sometime this week (maybe even later today)!

**Comment by chriskrycho** [comment]
Released as [v8.0.0](https://github.com/true-myth/true-myth/releases/tag/v8.0.0). Thanks again, @auvred!

**Pull request merged**
